### ISSUE TITLE
nav 제작 (11.22~11.24)

### ISSUE THREAD

**Issue by HM970506** [starter-valley/starter-valley-front#10]
## 작업 내용

- profileBox 제작
- menuBox 제작

## 작업 세부 사항

- [x] UI 컴포넌트 제작 및 CSS적용
     - [x] 픽셀에 따른 모바일 화면 구현
     - [x]  데스크탑 호버링 및 클릭시 색 전환 애니메이션 구현
- [x] nav router 처리
- [x] axios 필요한 부분 별도 처리

## 고민 사항

- api 더미 데이터 필요1: 로그인 이후 깃에서 받은 데이터를 그대로 전송받을 것인가? 아니면 별도의 json구조로 전송받을 것인가?

**Comment by HM970506** [comment]
![image](https://user-images.githubusercontent.com/62527898/203710341-2119be90-d7e3-4b74-b619-bae919180996.png)

![image](https://user-images.githubusercontent.com/62527898/203710408-d1278b6a-ea77-442c-a094-9f2364ab79ff.png)

**Comment by HM970506** [comment]
axios만 임시로 넣어두고 리액트 쿼리 처리는 아직 하지 않았어요~

**Comment by uuuuujin** [comment]
졸귀탱탱
